# Generated by Django 3.2.5 on 2021-07-15 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_category_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='url',
            field=models.SlugField(null=True, verbose_name='Ссилка на відео:'),
        ),
    ]
