# Generated by Django 3.2.5 on 2021-07-17 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_product_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='url',
            field=models.CharField(max_length=500, null=True, verbose_name='Ссилка на відео:'),
        ),
    ]
