# Generated by Django 3.2.5 on 2021-07-30 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_alter_product_url'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Raiting',
            new_name='Rating',
        ),
        migrations.AlterModelOptions(
            name='ratingstar',
            options={'ordering': ['-value'], 'verbose_name': 'Зірка рейтингу', 'verbose_name_plural': 'Зірки рейтингу'},
        ),
    ]
