# Generated by Django 3.2.5 on 2021-08-03 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_product_rating_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='rating_value',
        ),
    ]
